#22イベントレポートの追加
OthloTech/OthloTech pull request #177
Opened 2017-11-28 08:59 UTC by yuvernacrew

2017-11-28 10:00 UTC, Juju-62q requested changes
なんかレビューミスったんですけど下記以外LGTMです

2017-11-28 10:03 UTC, Juju-62q requested changes

2017-11-28 10:03 UTC, Juju-62q commented on content/events/othloevent22.md
> +まず初めに、が小学生の頃からYahoo!Japanで働いている時までのキャリアを面白おかしく話していただきました。<br>
ぱっと調べた感じYahoo!JAPANのほうがいいのかもしれません。
曖昧ですが会社としてはヤフー株式会社なんかな？(かなり曖昧だから気にしなくてもいいです)

2017-11-28 10:03 UTC, Juju-62q commented on content/events/othloevent22.md
> +まだ1ヶ月ありますので、食いの残さないように過ごしたいですね。
"悔い"ですね。

2017-11-30 03:40 UTC, Juju-62q approved these changes

2017-11-30 08:30 UTC, ryosism commented on content/events/othloevent22.md
> +まず初めに、が小学生の頃からYahoo!Japanで働いている時までのキャリアを面白おかしく話していただきました。<br>
「成田さんが」が抜けてるw

2017-12-01 04:41 UTC, hyde2able commented
@yuvernacrew 

画像のサイズが全て、オリジナル（4032x3000とか）のままで2MB近くあるから、横幅を1200pxにして縦横比固定でリサイズしてほしい！

それと、[Tinypng](https://tinypng.com/)で一度、画像の最適化をお願いします！

内容に関しては良いと思う！！33行目が「施設」じゃなくて「会場」のほうがしっくりするかなーくらい！

修正したらLGTM!

2017-12-07 17:52 UTC, merged