add report
OthloTech/OthloTech pull request #178
Opened 2017-12-11 15:04 UTC by Juju-62q

まだ集合写真はれてないですが文章だけでも。
![screen shot 2017-12-12 at 00 01 30-fullpage](https://user-images.githubusercontent.com/25079965/33837496-dbcb6c40-decf-11e7-970c-6c57b3626256.png)

2017-12-11 16:09 UTC, ryosism commented on content/events/othloevent23.md
> +
会社のホームページへのリンクとか貼っても良いかも！絶対必要ってわけではないけどね

2017-12-11 16:13 UTC, ryosism commented on content/events/othloevent23.md
> +聞くことが義務ではない気楽な感じもOthloTechならではではないでしょうか。
意識的に自由なLT会をやったのはあれが初めてだから、「ならでは」とは違う言葉で書いて欲しいー！

2017-12-11 16:16 UTC, ryosism commented on content/events/othloevent23.md
> +### KatsuakiTakagiさん「monacoinをはじめてみた」
monacoinの表記のブレがあるから、大文字か小文字か統一しよう

2017-12-11 16:39 UTC, ryosism reviewed
レポートお疲れ様、加筆修正よろしくお願い！
ちなみに集合写真を含め、いくつか写真をアップロードしたから使えるものは使ってくださいな！

2017-12-12 03:31 UTC, hyde2able commented
@Juju-62q 

バナー画像の配置は `static/images/banners/events/` 配下においてほしいな！
画像が全て、4000pxくらいだから、横幅最大1024pxで縦横比固定で、リサイズしてから画像の最適化してほしい！
https://tinypng.com/

拡張子が、`.JPG` で大文字なのがちょっと気になるけどそれはいいや

2017-12-12 08:53 UTC, haseaki0503 requested changes

2017-12-12 08:53 UTC, haseaki0503 commented on content/events/othloevent23.md
> +ご愛読ありがとうございました！
test

2017-12-12 08:59 UTC, haseaki0503 approved these changes

2017-12-12 09:10 UTC, ryosism approved these changes

2017-12-12 11:52 UTC, merged