Event/stmn
OthloTech/OthloTech pull request #179
Opened 2018-02-02 07:27 UTC by ShuzoTakahashi

REVIEW

2018-02-02 11:24 UTC, Juju-62q requested changes
記事の前にタイトルとか日付とかバナー情報とか抜けてるから記事が認識されてない感じする。
記事が読めないので動作確認してみるといいかも。
あとバナーのアップも！
![screenshot from 2018-02-02 20-17-18](https://user-images.githubusercontent.com/25079965/35730817-d854d71c-0856-11e8-8088-c5b78c5d3a74.png)

内容はまだそんなに呼んでないけど画像サイズが大きいからサイズを横1024にリサイズしてtinypngってサイトで圧縮かけると小さくなる。

最後にこれは俺のせいなんだけどLT会の記事のタイムテーブルのひでさんのLTにLの文字を追加してほしい笑

2018-02-02 15:16 UTC, ShuzoTakahashi commented
<img width="1971" alt="2018-02-03 0 07 45" src="https://user-images.githubusercontent.com/30533181/35739880-6f661e6c-0876-11e8-8303-3cb17dfa2f49.png">
なぜかバナーのサムネが消し飛んでしまうのですが、原因わかりませんか？

2018-02-02 15:20 UTC, yuvernacrew commented on content/events/othloevent24.md
> +{{< image src="/images/events/2017-01-27/e24-6.jpg" alt="オープニング" >}}
2018年だね！笑

2018-02-02 15:20 UTC, yuvernacrew commented on content/events/othloevent24.md
> +[【学生限定】UXデザイン講座（第1回）@アクアリング OthloEvent#25](https://othlotech.connpass.com/event/77216/)
改行した方が良いと思う！

2018-02-02 15:23 UTC, yuvernacrew commented
画像の最適化をおねがします！
(横幅を1200pxにして縦横比固定でリサイズ、[https://tinypng.com/](Tinypng)で最適化らしいです！私もcookpadの時言われた！笑)

2018-02-02 15:27 UTC, yuvernacrew commented
@ShuzoTakahashi 
私みれてるよー！
<img width="1019" alt="2018-02-03 0 25 21" src="https://user-images.githubusercontent.com/18437884/35740689-f5bfd8b6-0878-11e8-98d2-ed314e9dc442.png">

2018-02-02 15:28 UTC, cheez921 requested changes
- コメント確認
- 最適化
をお願いします！
(reviewミスってごめん！)

2018-02-02 15:31 UTC, ShuzoTakahashi commented
あ、リサイズ忘れてました。
そこのサイトで圧縮はかけました。

2018-02-02 16:50 UTC, cheez921 approved these changes
リンクの改行したら、LGTM👍

2018-02-02 16:54 UTC, ShuzoTakahashi commented
ありがとうございます！

2018-02-03 01:53 UTC, Juju-62q approved these changes
LGTMです

2018-02-03 06:26 UTC, merged