OthloEvent#25のイベントレポート
OthloTech/OthloTech pull request #181
Opened 2018-02-19 13:54 UTC by yuvernacrew

2018-02-20 00:12 UTC, haseaki0503 requested changes

2018-02-20 00:12 UTC, haseaki0503 commented on content/events/othloevent25.md
> +まずはオフィスをお貸しいただいた[アクアリング](http://www.aquaring.co.jp/) さんのご紹介から。
オフィスだけじゃなくて、吉橋先生を呼んでいただいたり、内容もすべてアクアリングさんです

2018-02-20 00:12 UTC, haseaki0503 commented on content/events/othloevent25.md
> +このように、根本的なUXについての説明から、多摩美術大学の生徒さんの作品など、具体的に良いUXについて教えていただきました。作品例を見せていただいてわかりやすく、UXのことを全く知らない初心者の人でも理解しやすい内容でした！
根本的なUX → UXの根本

2018-02-20 00:12 UTC, haseaki0503 commented on content/events/othloevent25.md
> +第三部は先ほどご講義いただいた方たちによるディスカッションで、テーマは**「UXデザインをモノづくりに活かすために」**でした！
先ほどご講義いただいた、吉橋先生、遠藤さん、林さんによる

2018-02-20 00:12 UTC, haseaki0503 commented on content/events/othloevent25.md
> +今回ご講義いただいた吉橋さん、講義をしていただき、飲み物や食べ物をご提供していただいたアクアリングさん、本当にありがとうございました！
吉橋さん→吉橋先生、飲み物や食べ物をご提供していただいた→ご協力/ご協賛いただいた

2018-02-20 00:12 UTC, haseaki0503 commented on content/events/othloevent25.md
> +実際に働くにあたってのwebサイトの構築についてから、ターゲットユーザーの分析など、webサイトを作るにあたっての重要なことについてご講義いただきました。学生にとっては会社としてどのようにwebサイトを作成しているかなど非常に気になる点であり、デザインする前段階の話をお聞かせいただいて、とても勉強になりました！実際に作られたwebサイトのデザインについても教えていただきました！
実務でのwebサイトのつくりかたと、webサイトをつくるにあたって重要なターゲットユーザーの分析などの手法についてご講義いただきました。
学生にとっては、会社としてどのようにwebサイトをつくっているのかは非常に気になる点であり、デザインの方法だけでなく、デザインする前の段階からお話を聞かせていただいて、とても勉強になりました！実際に、アクアリングさんがつくられたwebサイトのデザインについても教えていただきました！

2018-02-20 04:03 UTC, ShuzoCreate requested changes

2018-02-20 04:03 UTC, ShuzoTakahashi commented on content/events/othloevent25.md
> +このように、根本的なUXについての説明から、多摩美術大学の生徒さんの作品など、具体的に良いUXについて教えていただきました。作品例を見せていただいてわかりやすく、UXのことを全く知らない初心者の人でも理解しやすい内容でした！
＞＞多摩美術大学の生徒さんの作品など、具体的に良いUXについて教えていただきました。作品例を見せていただいて〜

軽く作品の内容にも触れたほうが良いような気がする

2018-02-20 04:40 UTC, ShuzoTakahashi commented
あと、画像サイズを1024以下にしなくては駄目らしい

2018-02-21 11:50 UTC, haseaki0503 approved these changes

2018-02-22 12:39 UTC, ShuzoCreate approved these changes

2018-02-24 09:07 UTC, merged