Events/27 abema tv
OthloTech/OthloTech pull request #188
Opened 2018-03-31 06:07 UTC by asukaokochi

abemaTVのレポートを書きました！よろしくお願いします！

2018-03-31 07:09 UTC, cheez921 requested changes
以下の点、訂正お願いします！

2018-03-31 07:09 UTC, cheez921 commented on content/events/othloevent27.md
> +{{< image src="/images/events/2018-02-18/othlo-event27-1.png" alt="イベントバナー" >}}
リンク切れしてる！
images/banners/events/othlo-event27-1.pngあたりのをとるか、/images/events/2018-03-25/にbannerを格納するかで対応しましょう！

2018-03-31 07:09 UTC, cheez921 commented on content/events/othloevent27.md
> +初めに、AbemaTV 開発本部長の長瀬さんに発表していただきました！
写真を二枚入れる場合は、説明を画像の前に書いたほうがよいかも！

2018-03-31 07:09 UTC, cheez921 commented on content/events/othloevent27.md
> +初めに、AbemaTV 開発本部長の長瀬さんに発表していただきました！
てか多分だけど、figureタグの下にテキストを入れる場合`<p></p>`に入らなくてスタイルがあたってない。
やで、画像の下は一行改行せんとあかん仕様やな笑

2018-03-31 07:09 UTC, yuvernacrew commented on content/events/othloevent27.md
> +Githubのスター数によるインセンティブ制度や、エンジニア・クリエイター向けカンファレンスの開催など、エンジニアにとって働きやすい環境が整っているようでした。
「整っているようでした。」がなんか違和感感じた(自分日本語苦手な日本人のため参考にはならんかも笑)
「整っているみたいですね。」とか「整っていることがわかりました。」の方がよいかな。
ちょっと読み直してみてほしいです！

2018-03-31 07:09 UTC, yuvernacrew commented on content/events/othloevent27.md
> +次に、AbemaTV エンジニアの鈴木さんに発表していただきました！
同じくここもスタイルが当たってないので、画像の前にするか、改行するかで対応をおねがいします！

2018-03-31 07:09 UTC, yuvernacrew commented on content/events/othloevent27.md
> +LT会の様子はこちら
この後に改行を入れた方が親切かな。

2018-03-31 07:09 UTC, yuvernacrew commented on content/events/othloevent27.md
> +次回はNVIDIA様の学習コンテンツを使った機械学習のハンズオンを行います！ぜひお越しください！
この後も改行を入れた方が親切！

2018-03-31 07:12 UTC, yuvernacrew commented
あと、画像はwidthを1024px、できたら画像自体をもう少し明るくしてくれるとありがたい。

2018-03-31 07:59 UTC, haseaki0503 requested changes
内容について、思ったこと・考えたことを入れるとより良くなると思います

2018-03-31 09:14 UTC, yoshikawa requested changes
@yuvernacrew が指摘しているところが気になりました。
バナーと改行と画像の修正をお願いします。
自分の感想を少し交えて良いイベントレポートにしましょう！

2018-03-31 09:14 UTC, YoshikawaTaiki commented on content/events/othloevent27.md
> +{{< image src="/images/events/2018-02-18/othlo-event27-1.png" alt="イベントバナー" >}}
{{< image src="/images/banners/events/othlo-event27-1.png" alt="イベントバナー" >}} で良いと思います

2018-04-01 01:31 UTC, haseaki0503 approved these changes

2018-04-01 03:05 UTC, yoshikawa approved these changes

2018-04-01 03:14 UTC, yoshikawa requested changes
まだ画像がnot foundになってる。/入ってないだけだから、直していいかな？

2018-04-01 03:14 UTC, YoshikawaTaiki commented on content/events/othloevent27.md
> +{{< image src="images/banners/events/othlo-event27-1.png" alt="イベントバナー" >}}
{{< image src="/images/banners/events/othlo-event27-1.png" alt="イベントバナー" >}}

2018-04-01 03:14 UTC, YoshikawaTaiki commented on content/events/othloevent27.md
> +banner = "images/banners/events/othlo-event27-1.png"
banner = "/images/banners/events/othlo-event27-1.png"

2018-04-01 05:07 UTC, asukaokochi commented on content/events/othloevent27.md
> +{{< image src="images/banners/events/othlo-event27-1.png" alt="イベントバナー" >}}
助かります;;ありがとうございます！！

2018-04-01 06:43 UTC, yoshikawa approved these changes

2018-04-01 08:21 UTC, cheez921 approved these changes

2018-04-04 15:20 UTC, merged