NVIDIAのイベントレポート初稿
OthloTech/OthloTech pull request #189
Opened 2018-04-30 18:06 UTC by ryosism

大変長らくお待たせしました･･･！NVIDIAのイベントレポート書いたから、変なとことか無いか見てほしい！

2018-05-02 00:23 UTC, Juju-62q requested changes

2018-05-02 00:23 UTC, Juju-62q commented on content/events/othloevent28.md
> +5/27(日)に株式会社ピクシブと一緒に、画像処理配信技術(ImageFlux)の勉強会&ハンズオンを行います！
今までの記事の感じだと企業名としては敬称つけてるので様つけた方が良さそうです

2018-05-02 00:23 UTC, Juju-62q commented on content/events/othloevent28.md
> +イラスト投稿SNSとして有名なPixivさんとの勉強会、質とレベルの高い知識を得られそうです。<br>
会社名としてはピクシブ、SNS名としてはpixivでおねがいします。

2018-05-02 09:34 UTC, yoshikawa requested changes
2つ気になるところがあったので、修正おねがいします🙏

2018-05-02 09:34 UTC, YoshikawaTaiki commented on content/events/othloevent28.md
> +5/27(日)に株式会社ピクシブ様と一緒に、画像処理配信技術(ImageFlux)の勉強会&ハンズオンを行います！
5/27の表記がなんか、おかしいので5月27日（日）にしてくれると嬉しいです。

2018-05-02 09:34 UTC, YoshikawaTaiki commented on content/events/othloevent28.md
> +イラスト投稿SNSとして有名なpixivさんとの勉強会、質とレベルの高い知識を得られそうです。<br>
ピクシブで統一するんでしたっけ？

2018-05-02 12:49 UTC, ryosism commented on content/events/othloevent28.md
> +イラスト投稿SNSとして有名なpixivさんとの勉強会、質とレベルの高い知識を得られそうです。<br>
会社名のことー？社名統一のことはよく聞いてないんだけど、どんな感じなの？ @Juju-62q @haseaki0503

2018-05-02 13:28 UTC, Juju-62q commented on content/events/othloevent28.md
> +イラスト投稿SNSとして有名なpixivさんとの勉強会、質とレベルの高い知識を得られそうです。<br>
会社名としてはピクシブ、SNS名としてはpixivでおねがいします。

2018-05-02 13:29 UTC, Juju-62q commented
PC死んだので実行できなくなりました。なるはやで構築します。

2018-05-03 03:23 UTC, yoshikawa requested changes

2018-05-03 03:23 UTC, yoshikawa commented on content/events/othloevent28.md
>  イラスト投稿SNSとして有名なpixivさんとの勉強会、質とレベルの高い知識を得られそうです。<br>
ここも `ピクシブ様` に直したほうが良さそう

2018-05-04 07:25 UTC, Juju-62q commented on content/events/othloevent28.md
> +イラスト投稿SNSとして有名なピクシブ様との勉強会、質とレベルの高い知識を得られそうです。<br>
会社名のみにするとこの文言には違和感が出そうです

```
イラスト投稿SNSのpixiv等で有名なピクシブ様
```

とかのほうが自然なのかな？
少し微妙な判断ですが

2018-05-04 13:00 UTC, ryosism commented on content/events/othloevent28.md
> +イラスト投稿SNSとして有名なピクシブ様との勉強会、質とレベルの高い知識を得られそうです。<br>
微妙かもしれないけど、それが一番無難かな！ありがとう〜

2018-05-04 13:02 UTC, ryosism commented
修正done、あと<br>をスペース2個分に置換しました~

2018-05-05 07:45 UTC, Juju-62q approved these changes

2018-05-05 09:03 UTC, yoshikawa approved these changes

2018-05-08 07:30 UTC, merged