Othlo event29のイベントレポート
OthloTech/OthloTech pull request #190
Opened 2018-05-02 03:47 UTC by ozaki-physics

アップルップルのイベントレポートのチェックをお願いします。

2018-05-02 05:52 UTC, ShuzoTakahashi commented
> アップルップルさんは、Webサイトの受託制作をしながら、Web制作者が便利に使えるCMSの開発や、セミナーの主催、サポートをするための場所の提供といった業務を行っています。

「Webサイトの受託制作のほか」とかの方が良くない？

> 質問は随時受け付けていただけて、sli.doというサービスを利用しました。
なんか文章がぎこちない...

> 体験談に基づくお話だったため、身近に感じ、自分もやってみようととても感じました。
体験に基づくお話が「体験談」

> 工夫次第どのようにも使え、とても便利だと思いました。
使えてとても便利

2018-05-02 06:03 UTC, ShuzoCreate requested changes

2018-05-02 06:03 UTC, ShuzoTakahashi commented on content/events/othloevent29.md
> +
> アップルップルさんは、Webサイトの受託制作をしながら、Web制作者が便利に使えるCMSの開発や、セミナーの主催、サポートをするための場所の提供といった業務を行っています。

「Webサイトの受託制作のほか」とかの方が良くないかな

> 質問は随時受け付けていただけて、sli.doというサービスを利用しました。

なんか文章がぎこちない...

2018-05-02 06:03 UTC, ShuzoTakahashi commented on content/events/othloevent29.md
> +私の心に残った言葉は、「気になったことはすぐに試そう」でした!<br>
> 体験談に基づくお話だったため、身近に感じ、自分もやってみようととても感じました。

体験に基づくお話が「体験談」

2018-05-02 06:03 UTC, ShuzoTakahashi commented on content/events/othloevent29.md
> +{{< image src="/images/events/2018-04-29/seminar.jpg" alt="ワークショップ風景" >}}
> 工夫次第どのようにも使え、とても便利だと思いました。

使えてとても便利、でいいのでは

2018-05-02 09:42 UTC, yoshikawa reviewed
個人的な意見だけど、改行が必要なところがいくつかありそう。

2018-05-02 09:42 UTC, YoshikawaTaiki commented on content/events/othloevent29.md
> +イベント内容は、アップルップルのエンジニアとデザイナーの方に、ご講演いただきました。
個人的な意見だけど、改行がないところがあるので、ぎっしりな記事になっちゃってる気がする。

2018-05-02 09:45 UTC, ShuzoCreate requested changes

2018-05-02 09:45 UTC, ShuzoTakahashi commented on content/events/othloevent29.md
> +PWAによってユーザーは、Webページなのにアプリのような感覚で操作できます。
> PWAとは、モバイル端末でページを表示する時に、ネイティブアプリのような動きができる技術です。 PWAによってユーザーは、Webページなのにアプリのような感覚で操作できます。

この文章まとめれる希ガス

2018-05-02 09:46 UTC, ShuzoTakahashi commented on content/events/othloevent29.md
> +イベント内容は、アップルップルのエンジニアとデザイナーの方に、ご講演いただきました。
あと、全体的に句点が多すぎるような気もする

2018-05-02 11:31 UTC, cheez921 requested changes
ごめんなさい更新前のもあると思う。

2018-05-02 11:31 UTC, cheez921 commented on content/events/othloevent29.md
> +今回は、2018/04/29に行われた「[【学生限定】アップルップルのWeb技術の学び方講座 OthloEvent#29](https://othlotech.connpass.com/event/85253/)」のイベントレポートをお届けします!
>今回は、2018/04/29に行われた

なんか文章中にyyyy/MM/ddの表記あるの読みづらさを感じた。
ふつーに4月29日でいいんじゃないかな。

2018-05-02 11:31 UTC, cheez921 commented on content/events/othloevent29.md
> +アップルップルさんは、Webサイトの受託制作をしながら、Web制作者が便利に使えるCMSの開発や、セミナーの主催、サポートをするための場所の提供といった業務を行っています。<br>
> 業務を行なっています

中の人みたい笑
もう少し軽く、「アップルップルさんは、Webサイト制作やCMSの開発や、セミナーの主催、サポートをするための場所の提供等を行なっている会社です」くらいでええんちゃうかな。

2018-05-02 11:31 UTC, cheez921 commented on content/events/othloevent29.md
> +そのあとのワークショップでは、情報収集のやり方を学びました。
やり方 -> 方法 の方がしっくりきた

2018-05-02 11:31 UTC, cheez921 commented on content/events/othloevent29.md
> +そのあとのワークショップでは、情報収集のやり方を学びました。
なんか、ワークショップもイベントの内容に含まれるで、イベント内容は〜で入るのに違和感がある。

イベントでは、アップルップルのエンジニアとデザイナーの方にご講演いただき、そのあとワークショップにて情報収集の方法を学びました。 とか？

2018-05-02 11:31 UTC, cheez921 commented on content/events/othloevent29.md
> +
会場からの質問を匿名で集められる[sli.do](https://www.sli.do/)というサービスを用いてイベントを進めて行きました。とか？(参考として書いてるだけなんで、使うんだったらそのまま使うんじゃなくて自分の言葉に変えてね。)

2018-05-02 11:31 UTC, cheez921 commented on content/events/othloevent29.md
> +最近は、SPA (Single Page Application) とPWA (Progressive Web App) が注目を浴びていて、それに関連する内容でした。<br>
公演の内容に関して言いたいんだと思うんだけど、
この書き方だとSPAとPWAに関しての公演なんだな〜って思わせるけど、実際は他の技術についての話もたくさんあったよね？
もう少しわかりやすい日本語にしてほしいかな。

2018-05-02 11:31 UTC, cheez921 commented on content/events/othloevent29.md
> +PWAとは、モバイル端末でページを表示する時に、ネイティブアプリのような動きができる技術です。
PWAって技術というより、しくみかな？

2018-05-02 11:31 UTC, cheez921 commented on content/events/othloevent29.md
> +他にもWebで音声認識やビデオチャットができたり、スマホの加速度センサーを利用できるようです。<br>
なんか主語がわかりづらい。
PWAの話なのかな？って思わせちゃうかも。

2018-05-02 11:44 UTC, cheez921 requested changes

2018-05-02 11:44 UTC, yuvernacrew commented on content/events/othloevent29.md
> +<br>
br重ねて使うのやめましょう。
改行したら別の<p>で囲まれるので必要がないお

2018-05-02 11:44 UTC, yuvernacrew commented on content/events/othloevent29.md
> +アップルップルさんは、Webサイトの受託制作のほか、Web制作者が便利に使えるCMSの開発や、セミナーの主催、サポートをするための場所の提供といった業務を行っています。<br>
業務を行なっています。 -> ことをしている会社です。
でいいと思う。

2018-05-02 11:44 UTC, yuvernacrew commented on content/events/othloevent29.md
> +講演スライド([https://www.slideshare.net/mkasumi/ss-95413237](https://www.slideshare.net/mkasumi/ss-95413237))
埋め込んじゃったら...？

2018-05-02 11:44 UTC, yuvernacrew commented on content/events/othloevent29.md
> +<!--他になんか書けるイベントあったっけ?-->
現時点ではこれだけなので、コメントを消し忘れないように気をつけてね！

2018-05-02 15:07 UTC, ozaki-physics commented on content/events/othloevent29.md
> +最近は、SPA (Single Page Application) とPWA (Progressive Web App) が注目を浴びていて、それに関連する内容でした。<br>
無知ゆえあれ以外のを文章化できなかった...　ヘルプ

2018-05-02 15:11 UTC, ozaki-physics commented on content/events/othloevent29.md
> +講演スライド([https://www.slideshare.net/mkasumi/ss-95413237](https://www.slideshare.net/mkasumi/ss-95413237))
なんでも埋め込んじゃったら安心感がないかなって思って今回は明記してみたけど変えた方がいい?

2018-05-03 15:21 UTC, yuvernacrew commented on content/events/othloevent29.md
> +講演スライド([https://www.slideshare.net/mkasumi/ss-95413237](https://www.slideshare.net/mkasumi/ss-95413237))
安心感とは...？

2018-05-03 15:29 UTC, yuvernacrew commented on content/events/othloevent29.md
> +アップルップルさんは、Webサイト作成やCMSの開発、セミナーの主催、勉強をサポートをするための場所の提供等を行なっている会社です。<br>
改行前のbrはいらないかな。

2018-05-03 15:29 UTC, yuvernacrew commented on content/events/othloevent29.md
> +今回紹介されたWebページの一覧([https://hackmd.io/s/S1JT9dxaf](https://hackmd.io/s/S1JT9dxaf))
([https://hackmd.io/s/S1JT9dxaf](https://hackmd.io/s/S1JT9dxaf))
は([hackmd.io](https://hackmd.io/s/S1JT9dxaf))でもいいんじゃないかなっておもった。

それか、
今回紹介されたWebページの一覧は[こちら](https://hackmd.io/s/S1JT9dxaf)です。とか？

2018-05-03 15:29 UTC, yuvernacrew commented on content/events/othloevent29.md
> +<br>
br消し忘れてる！

2018-05-03 15:29 UTC, yuvernacrew commented
<br><br>の消し忘れを見直してください。
あとは、コメントしたところくらいかな〜

2018-05-03 16:06 UTC, ShuzoTakahashi commented
ここに```<br>```を普通に書くとmd対応だから普通に改行されとる笑
てかそもそもスペース4つじゃ改行できない感じ？

2018-05-04 06:42 UTC, ozaki-physics commented
スペース4つで改行できると思わなかった(笑)
始めにHTMLで書いてたから<br>を乱用したの。

2018-05-04 07:41 UTC, ShuzoCreate approved these changes

2018-05-04 07:41 UTC, ShuzoCreate commented on content/events/othloevent29.md
> +アップルップルさんからドローンを貸していただけて、遊んだりもしました(笑)<br>
> アップルップルさんからドローンを貸していただけて、遊んだりもしました(笑)

貸していただいて

2018-05-04 07:43 UTC, ShuzoCreate approved these changes

2018-05-04 07:43 UTC, ShuzoCreate approved these changes

2018-05-04 07:44 UTC, ShuzoCreate approved these changes

2018-05-04 08:30 UTC, haseaki0503 approved these changes

2018-05-04 10:47 UTC, yuvernacrew commented on content/events/othloevent29.md
> +会場からの質問を匿名かつ随時できるように[sli.do](https://www.sli.do/)というサービスを利用し、活気ある講演になったと思います。<br>
> 会場からの質問を匿名かつ随時できるように[sli.do](https://www.sli.do/)というサービスを利用し

  #ちょっと違和感を感じた。
「会場からの質問を、匿名で随時受け取ることのできる[sli.do](https://www.sli.do/)というサービスを利用し」

2018-05-04 10:47 UTC, yuvernacrew commented on content/events/othloevent29.md
> +講演に使われたスライドは[こちら](https://www.slideshare.net/mkasumi/ss-95413237))で公開されています。
[こちら](https://www.slideshare.net/mkasumi/ss-95413237))
の最後のかっこいらないよ

2018-05-06 02:57 UTC, cheez921 approved these changes

2018-05-10 07:39 UTC, merged