[add] ピクシブイベントレポート
OthloTech/OthloTech pull request #192
Opened 2018-05-29 18:04 UTC by ShuzoTakahashi

2018-05-29 23:24 UTC, haseaki0503 requested changes

2018-05-29 23:24 UTC, haseaki0503 commented on content/events/othloevent30.md
> +・ 画像の表示速度を一定にするために、一度オリジナル画像から  1200px*1200pxの「マスタ画像」を生成し、そこからサムネイルの生成
表示速度=処理速度 とか書いた方が良さそう

2018-05-29 23:24 UTC, haseaki0503 commented on content/events/othloevent30.md
> +実際にImageFluxで画像圧縮&加工を体験してみます。
加工の種類を知りたいです

2018-05-29 23:24 UTC, haseaki0503 commented on content/events/othloevent30.md
> +今回はの[UXデザインの教科書](https://www.amazon.co.jp/UX%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3%E3%81%AE%E6%95%99%E7%A7%91%E6%9B%B8-%E5%AE%89%E8%97%A4-%E6%98%8C%E4%B9%9F/dp/4621300377)の著者、千葉工大教授 安藤 昌也をお呼びします。<b>「第二
ので、のでなので、「大丈夫です。」と一旦文章切りたい

2018-05-30 00:14 UTC, Juju-62q requested changes
このくらい。乙。

2018-05-30 00:14 UTC, Juju-62q commented on content/events/othloevent30.md
> +また、特定の企画部が存在せず、エンジニア一人ひとりの裁量が大きく、ボトムアップ型で事業アイデアが生まれて行くそうです。
"一人ひとり"はなんか違和感ある
ひとりひとりか一人一人かな？

2018-05-30 00:14 UTC, Juju-62q commented on content/events/othloevent30.md
> +<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">キャッシャブルにかこう<a href="https://twitter.com/hashtag/OthloTech?src=hash&amp;ref_src=twsrc%5Etfw">#OthloTech</a> <a href="https://twi
俺だけタイトルのツイートじゃないのはなぜだろうか

2018-05-30 00:14 UTC, Juju-62q commented on content/events/othloevent30.md
> +ピクシブでは「社内のコミュニケーション」や「社員の成長」などを重視していて、その一環としてユニークな取り組みを多数実施しているそうです。
なにかしらで公式サイトのせるほうがいい気がする
https://www.pixiv.co.jp/

2018-05-30 02:04 UTC, ShuzoTakahashi commented on content/events/othloevent30.md
> +また、特定の企画部が存在せず、エンジニア一人ひとりの裁量が大きく、ボトムアップ型で事業アイデアが生まれて行くそうです。
それ書いてるときに思って、ググったんだけど、問題なさげ

http://kanjibunka.com/kanji-faq/old-faq/q0436/

2018-05-30 04:27 UTC, yoshikawa requested changes
レビューしました！修正お願いします🙏

2018-05-30 04:27 UTC, YoshikawaTaiki commented on content/events/othloevent30.md
> +5/27に開催された[【学生限定】画像配信勉強会@ピクシブ OthloEvent#30](https://othlotech.connpass.com/event/85753/)のイベントレポートです。
5/27(日)に表記変えても良いかも！

2018-05-30 04:27 UTC, YoshikawaTaiki commented on content/events/othloevent30.md
> +・ 高速なアセンブラ（に近いC）のリソースを活かすためにcgoの採用
cgoってGolangでC言語を使いたいから、Cの疑似パッケージを取り入れるんだよね？
C言語を書くためにcgoがある感じなので、文章変えたほうが良いかも
「C（言語で動く）パッケージを使いたいのでcgoの採用」になるのかな？
https://golang.org/cmd/cgo/

2018-05-30 04:27 UTC, YoshikawaTaiki commented on content/events/othloevent30.md
> +[【学生限定】Webインフラ入門 @クックパッド OthloEvent#31](https://othlotech.connpass.com/event/87047/)
.が4つあると...と.一つの間に謎の空白が生まれてたので、一応報告！

2018-05-30 04:32 UTC, YoshikawaTaiki commented on content/events/othloevent30.md
> +ピクシブでは[サマーインターン](https://recruit.pixiv.net/intern/tech/)を日程8月22日（水）～ 8月28日（火）と9月05日（水）～ 9月11日（火）の２つの期間で募集しているそうです。コースや期間が合わない場合は要相談のもと柔軟に対応してくださるとのことです！
公式サイト9.05って書いてあるけど、9月05日って書くと、なんか変な感じする

2018-05-30 04:33 UTC, Juju-62q commented on content/events/othloevent30.md
> +・ 高速なアセンブラ（に近いC）のリソースを活かすためにcgoの採用
C(意味わかんないくらいチューニングされて実質アセンブラ)っていってたからどちらでもよさそう

2018-05-30 08:48 UTC, ShuzoTakahashi commented on content/events/othloevent30.md
> +・ 高速なアセンブラ（に近いC）のリソースを活かすためにcgoの採用
単純にCというより、ほぼアセンブラってこと伝えたいかも

2018-05-30 08:49 UTC, ShuzoTakahashi commented on content/events/othloevent30.md
> +ピクシブでは[サマーインターン](https://recruit.pixiv.net/intern/tech/)を日程8月22日（水）～ 8月28日（火）と9月05日（水）～ 9月11日（火）の２つの期間で募集しているそうです。コースや期間が合わない場合は要相談のもと柔軟に対応してくださるとのことです！
公式サイトの[募集概要](https://recruit.pixiv.net/intern/tech/)からコピペした

2018-05-30 09:25 UTC, ShuzoCreate commented on content/events/othloevent30.md
> +<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">キャッシャブルにかこう<a href="https://twitter.com/hashtag/OthloTech?src=hash&amp;ref_src=twsrc%5Etfw">#OthloTech</a> <a href="https://twi
ツイートされてない...

2018-05-30 09:40 UTC, ShuzoTakahashi commented on content/events/othloevent30.md
> +・ 高速なアセンブラ（に近いC）のリソースを活かすためにcgoの採用
こんな感じはどう？
> 高速なCプログラム（ほぼアセンブラ）のリソースを活かすためにcgoの採用

2018-05-30 09:40 UTC, Juju-62q commented on content/events/othloevent30.md
> +<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">キャッシャブルにかこう<a href="https://twitter.com/hashtag/OthloTech?src=hash&amp;ref_src=twsrc%5Etfw">#OthloTech</a> <a href="https://twi
https://twitter.com/OthloTech/status/1000653462474899456

2018-05-30 09:46 UTC, Juju-62q commented on content/events/othloevent30.md
> +・ 高速なアセンブラ（に近いC）のリソースを活かすためにcgoの採用
Cで書かれた、あるいはCで解読可能なライブラリを使う為だから吉川の文言でいい気がして来た

2018-05-30 09:46 UTC, Juju-62q commented on content/events/othloevent30.md
> +ピクシブでは[サマーインターン](https://recruit.pixiv.net/intern/tech/)を日程8月22日（水）～ 8月28日（火）と9月05日（水）～ 9月11日（火）の２つの期間で募集しているそうです。コースや期間が合わない場合は要相談のもと柔軟に対応してくださるとのことです！
まぁ書かないから消せば良さそう

2018-05-30 09:50 UTC, ShuzoTakahashi commented on content/events/othloevent30.md
> +・ 高速なアセンブラ（に近いC）のリソースを活かすためにcgoの採用
おっけー！

2018-05-30 09:50 UTC, ShuzoTakahashi commented on content/events/othloevent30.md
> +ピクシブでは[サマーインターン](https://recruit.pixiv.net/intern/tech/)を日程8月22日（水）～ 8月28日（火）と9月05日（水）～ 9月11日（火）の２つの期間で募集しているそうです。コースや期間が合わない場合は要相談のもと柔軟に対応してくださるとのことです！
けした！

2018-05-31 15:56 UTC, Juju-62q approved these changes
LG!写真来てないけど

2018-06-02 05:53 UTC, YoshikawaTaiki commented
LG! 集合写真の追加お願いします👍👍

2018-06-02 05:53 UTC, yoshikawa approved these changes

2018-06-02 10:07 UTC, Juju-62q requested changes
ん？ごめんweb上でしか見てないけど写真あがってる？

2018-06-02 10:28 UTC, ShuzoTakahashi commented
うわ、絶対ステージングし忘れた。
ロード乗ってるから家帰ったら再pushします...

2018-06-05 12:39 UTC, haseaki0503 requested changes

2018-06-05 12:39 UTC, haseaki0503 commented on content/events/othloevent30.md
> +実際にImageFluxで画像圧縮や拡大縮小、回転などを体験してみます。
> 画像"の"圧縮や拡大・縮小、回転などを体験してみます
のほうがわかりやすそうです。

2018-06-07 07:07 UTC, YoshikawaTaiki commented
修正確認!

2018-06-07 09:46 UTC, Juju-62q approved these changes
OKです

2018-06-08 15:29 UTC, haseaki0503 approved these changes

2018-06-08 17:39 UTC, merged