クックパッドイベントレポートの追加
OthloTech/OthloTech pull request #194
Opened 2018-06-18 14:18 UTC by Juju-62q

クックパッドのイベントレポート書いた。

![image](https://user-images.githubusercontent.com/25079965/41541589-c72e91e6-734d-11e8-94bc-906363c72430.png)

2018-06-18 14:23 UTC, yoshikawa reviewed
レビューしました.さすがはやい!

2018-06-18 14:23 UTC, YoshikawaTaiki commented on content/events/othloevent31.md
> +クックパッド様にAWSの環境をご用意いただきWebインフラのハンズオンがスタートです！講師にはCTOの成田一生さん、インフラ部長の星 北斗さん、SREとして働いている吉川 竜太さんにお越しいただきました。「1日でWebインフラのプロにします」と言う星さんの言葉の通りハンズオンはかなりボリューミー内容です笑
名字と名前の間に空白の有無の統一をお願いします

2018-06-18 14:23 UTC, YoshikawaTaiki commented on content/events/othloevent31.md
> +また、クックパッドで実際にどのようにモニタリングをしているのか、障害対応をしているのかと言うこともお話として聞くことができました。メトリクス監視の様子もインスタ映えしていい感じです！笑
言うことも聞くことができました。のほうがいいかもしれません.

2018-06-18 15:35 UTC, yuvernacrew commented on content/events/othloevent31.md
> +今回のイベントはクックパッド株式会社様にご協力いただき、AWSを利用したWebアプリケーション入門ハンズオンを行いました。
Webアプリケーション入門 -> Webインフラ入門 
最初はタイトルに合わせた方がいいのかなって思った。
AWSにインフラ的な意味が込められているのだったら大丈夫かもしれんけど、
イベントもほぼインフラ周りだったし、webアプリ入門だとrails書くイベントだったのかな？って思うかもしれない！

2018-06-18 15:35 UTC, yuvernacrew commented on content/events/othloevent31.md
> +クックパッド様にAWSの環境をご用意いただきWebインフラのハンズオンがスタートです！講師にはCTOの成田 一生さん、インフラ部長の星 北斗さん、SREとして働いている吉川 竜太さんにお越しいただきました。「1日でWebインフラのプロにします」と言う星さんの言葉の通りハンズオンはかなりボリューミー内容です笑
ボリューミーって言葉は良い意味でも悪い意味でも使われるから、もっと良い言い回しがあるかなって思った。
内容が濃いとか、充実しているとかかな。。。
引き出しが少なくて申し訳ない笑

2018-06-18 15:35 UTC, yuvernacrew commented on content/events/othloevent31.md
> +がかなり心に残っています。エンジニアである以上証拠や論理に基づいて行動していきたいですね！
少しだけ読みづらかったかも。
という(〇〇さんの)言葉がかなり心に残ってます。
の方がすんなり読みやすいかなっておもった！

2018-06-18 15:35 UTC, yuvernacrew commented on content/events/othloevent31.md
> +{{< image src="/images/events/2018-06-16/insta.jpg" alt="インスタ映え" >}}
インスタ映えwwwwwwwwww

2018-06-18 15:35 UTC, yuvernacrew commented on content/events/othloevent31.md
> +今回イベントを開催していただいたクックパッド株式会社様本当にありがとうございました。
今回イベントを開催していただいたクックパッド株式会社様、本当にありがとうございました。  
一文が長かったので「、」があった方がいいかなって思った。

2018-06-18 15:35 UTC, yuvernacrew commented on content/events/othloevent31.md
> +[【学生限定】UXデザイン講座（第2回）@アクアリング OthloEvent#32](https://othlotech.connpass.com/event/88836/)
下のイベントも同様、改行ができていないので変な感じになってる。

2018-06-18 15:35 UTC, yuvernacrew commented on content/events/othloevent31.md
> +千葉工業大学の教授を務めている安藤昌也先生を及びして、ユーザニーズについて学びます。第2回ではありますが第1回と内容は独立しており、初めてでも参加できるようになっています。UXを学びたい方は是非お越しください！
及びして -> お呼びして！！！

2018-06-18 15:35 UTC, yuvernacrew commented on content/events/othloevent31.md
> +6/16(土)に開催された[【学生限定】Webインフラ入門 @クックパッド OthloEvent#31](https://othlotech.connpass.com/event/87047/)のイベントレポートです。
なんか、読む流れで、〜です。〜です。が少し気持ち悪く感じた。
いつもとおんなじ感じで
>  イベントレポートをお届けします。

でいいんじゃないかな？

2018-06-18 15:35 UTC, yuvernacrew commented on content/events/othloevent31.md
> +クックパッド様にかなり豪華なオードブルをご用意いただいて懇親会です。さすが食に力を入れている会社です。
なんか、少し日本語がきになる。。。
> 懇親会では、クックパッド様にかなり豪華なオードブルをご用意していただきました。

とかどうかな？

2018-06-18 15:36 UTC, yuvernacrew commented
何よりも、イベントレポートを書いてくれてありがとう。
私絶対、具体的な内容のところかけない。本当に感謝。

2018-06-19 10:26 UTC, ryosism commented on content/events/othloevent31.md
> +|18:00|懇親会（軽食をご用意します）|
懇親会だけでいい気がする！タイムスケジュールであって行程説明じゃないしね

2018-06-19 10:50 UTC, ryosism reviewed
レポートありがとう！
あと強いていうなら、クックパッド様とクックパッド株式会社様の表記ゆれがちょっと気になるくらいかな！

2018-06-19 10:50 UTC, ryosism commented on content/events/othloevent31.md
>  {{< image src="/images/events/2018-06-16/handson.jpg" alt="ハンズオン" >}}
みんな「真剣に」のはずなのにいっちゃんが盛大にマック広げてて草･･･
代わりの写真があったらそっちの方がいいかも

2018-06-19 10:55 UTC, Juju-62q commented on content/events/othloevent31.md
>  {{< image src="/images/events/2018-06-16/handson.jpg" alt="ハンズオン" >}}
いっちゃんは写ってない気がする。
マックもゴミが残っているだけだから問題ないかと。
他の写真は画角がイマイチだったりサイズがイマイチだったり

2018-06-19 11:07 UTC, yoshikawa requested changes
僕が気になったのは、2箇所です

2018-06-19 11:07 UTC, YoshikawaTaiki commented on content/events/othloevent31.md
> +美味しそうなご飯とともにまずはかんぱーい！
特殊な文字が先頭に入っている

2018-06-19 11:07 UTC, YoshikawaTaiki commented on content/events/othloevent31.md
> +という言葉がかなり心に残っています。エンジニアである以上証拠や論理に基づいて行動していきたいですね！
エンジニアである以上、証拠や論理に基づいて　読点入れたほうが読みやすいと思いました。

2018-06-19 15:15 UTC, cheez921 requested changes
この一点のみで、LGTMです！

2018-06-19 15:15 UTC, yuvernacrew commented on content/events/othloevent31.md
> +[【【学生限定】Unity勉強会@ワンダープラネット OthloEvent#33](https://othlotech.connpass.com/event/90850/)
ここの【【がなおってない！

2018-06-20 02:35 UTC, cheez921 approved these changes

2018-06-20 03:47 UTC, yoshikawa approved these changes

2018-06-20 03:51 UTC, ryosism approved these changes
LG™️！

2018-06-21 06:43 UTC, merged