ワンプライベントレポート
OthloTech/OthloTech pull request #198
Opened 2018-07-10 14:25 UTC by Juju-62q

ワンプラのイベントレポート

![fireshot capture 19 - unity othloev_ - http___localhost_1313_events_othloevent33_](https://user-images.githubusercontent.com/25079965/42516114-4c454450-8498-11e8-9f1f-b9360338745f.png)

2018-07-11 01:02 UTC, yoshikawa requested changes

2018-07-11 01:02 UTC, YoshikawaTaiki commented on content/events/othloevent33.md
> +## 今後の OthloEventについて
今後の
空白入ってるけど、意図があるなら大丈夫です。

2018-07-11 01:02 UTC, YoshikawaTaiki commented on content/events/othloevent33.md
> +まだまだやりたいことはあるようですが、とりあえず「やるだけはやった！」という様子で大満足なハンズオンとなりました！
はせあきも言ってたけど、ここ気になるので修正お願いします🙏

2018-07-11 04:29 UTC, yoshikawa approved these changes

2018-07-11 04:33 UTC, haseaki0503 approved these changes

2018-07-11 08:30 UTC, ryosism approved these changes
LG™️！

2018-07-25 03:57 UTC, ryosism commented
ワンプラの西田さんに確認してもらって1000万DLに修正した！

2018-07-25 05:23 UTC, merged