[create]EventReport35-LIG
OthloTech/OthloTech pull request #199
Opened 2018-09-01 11:30 UTC by ShuzoTakahashi

2018-09-03 05:40 UTC, haseaki0503 approved these changes

2018-09-04 13:13 UTC, cheez921 requested changes
画像サイズでかいんで、圧縮してください。

2018-09-04 13:13 UTC, yuvernacrew commented on content/events/othloevent35.md
> +懇親会では数人の方にLTしていただきました。
画像の上に文章を書くのか、下に書くのかを統一してほしい。

2018-09-04 13:28 UTC, ozaki-physics reviewed
とだけあって、の修正をお願いします

2018-09-05 11:38 UTC, ozaki-physics approved these changes

2018-09-07 05:29 UTC, cheez921 approved these changes

2018-09-09 07:50 UTC, merged