[WIP]さくらインターネットさんのイベントレポート
OthloTech/OthloTech pull request #200
Opened 2018-09-02 12:48 UTC by YoshikawaTaiki

TODO
- [ ] イベント内容の追記。
- [ ] 講義画像の挿入。

2018-09-04 11:12 UTC, Juju-62q requested changes
おつかれっすー。これくらいかな？

2018-09-04 11:12 UTC, Juju-62q commented on content/events/othloevent34.md
> +講師を務めてくださる前佛雅人さんからホワイトボードに WordPress をどう構築していけばいいかなどを丁寧に教えてくださいました。
講義内容のメインはwordpressの構築方法ではないのでここは変更してほしい

2018-09-04 11:12 UTC, Juju-62q commented on content/events/othloevent34.md
> +Pod は k8s における基本的な最小構成単位。Pod は「群れ」という意味もあるよという豆知識も聞けました(知らなかった)
。があったりなかったりするのはあまりよくないかなと

2018-09-04 12:00 UTC, Juju-62q requested changes

2018-09-04 12:00 UTC, Juju-62q commented on content/events/othloevent34.md
> +講師を務めてくださる前佛雅人さんからホワイトボードにどうサーバ構築していけばいいかなどを丁寧に教えてくださいました。
抽象度を高くするとイベントレポートとしてはかなり陳腐なものに見えちゃう気がする。
具体的に例を挙げるとするのであれば

"Kubernetesの設計思想からkubeadamsを利用した具体的なクラスタ作成方法などを"

2018-09-04 12:01 UTC, Juju-62q requested changes

2018-09-04 12:01 UTC, Juju-62q commented on content/events/othloevent34.md
> +Docker コンテナ技術の詳しい説明が聞けるのも勉強会の良いところですね!
あー、これに関してはDockerは不要だね。rktとかの話もしていたはずだし、k8sはコンテナランタイムには依存していない。

2018-09-04 13:01 UTC, Juju-62q requested changes

2018-09-04 13:01 UTC, Juju-62q commented on content/events/othloevent34.md
> +講師を務めてくださる前佛雅人さんからホワイトボードにどうサーバ構築していけばいいかなどを丁寧に教えてくださいました。
箇条書きの部分はもとに戻していいよん

```
講師を務めてくださる前佛雅人さんからホワイトボードにどうサーバ構築していけばいいかなどを丁寧に教えてくださいました。
```

を

```
講師を務めていただいた前佛雅人さんに過去のWebアプリケーション構成の問題点とそれを解決するためのKubernetesの設計思想などを丁寧に教えていただきました。
```

意図としてはサーバの構築方法というめちゃくちゃ抽象的な概念を教えてもらったということをわざわざ記載するのはイベントレポートが陳腐なものになってしまうと考えたから。

2018-09-04 13:03 UTC, YoshikawaTaiki commented on content/events/othloevent34.md
> +講師を務めてくださる前佛雅人さんからホワイトボードにどうサーバ構築していけばいいかなどを丁寧に教えてくださいました。
特に何の意図もないので、詳しく書いたほうがいいですね

2018-09-04 13:06 UTC, Juju-62q approved these changes

2018-09-05 14:41 UTC, ShuzoCreate approved these changes

2018-09-05 15:02 UTC, ShuzoTakahashi commented
お疲れ様、LGTMです

2018-09-11 11:53 UTC, merged