Othlohack2018
OthloTech/OthloTech pull request #203
Opened 2018-11-12 20:11 UTC by ozaki-physics

OthloHack2018のレポート

2018-11-12 23:46 UTC, asukaokochi reviewed
レビューしました！
細かい点が多いですが、よろしくお願いします！

2018-11-12 23:46 UTC, asukaokochi commented on content/events/othlohack2018.md
> +やっほー!　こんにちはー!　OthloTechのオザキ([@sena0801masato](https://twitter.com/sena0801masato))です。<br>
```suggestion
やっほー!　こんにちはー!　OthloTechのオザキ([@sena0801masato](https://twitter.com/sena0801masato))です。  
```
他の部分にもありますが、\<br\>じゃなくて半角スペース２つの方に置き換えた方が良いと思います。
（どちらでも良いと思いますが、そういう話が前Othloで出てたので…）
一応、参考にしてください→http://inaz2.hatenablog.com/entry/2013/05/25/231204

2018-11-12 23:46 UTC, asukaokochi commented on content/events/othlohack2018.md
> +OthloHack2018は、約40名の学生が参加し、14社もの企業にご協賛していただき、**東海最大級** の学生限定ハッカソンとなりました。<br>
```suggestion
OthloHack2018は、約40名の学生が参加し、14社もの企業にご協賛いただき、**東海最大級** の学生限定ハッカソンとなりました。<br>
```
「ご協賛していただき」ではなく「ご協賛いただき」の方が日本語としておかしくないかなぁと感じました。

2018-11-12 23:46 UTC, asukaokochi commented on content/events/othlohack2018.md
> +そして、その花言葉を持つ花をオススメしてくれるというサービスでした。
```suggestion
そして、その花言葉を持つ花をオススメしてくれるというサービスでした。
```
ここら辺の文章がちぎれてるのが気になりました…。
「どのようなサービスかというと、手書きの手紙からその内容に合う花を選び花束を作ってくれるサービスです。」でサービスの概要説明してから「具体的には〜」で機械学習を説明するとかの方が文章の流れとしておかしくないかなと思いました！

2018-11-12 23:46 UTC, asukaokochi commented on content/events/othlohack2018.md
> +日頃からデザインを勉強している学生や、これからデザインを意識してみたい学生などなど、ぜひご参加ください!<br>
```suggestion
日頃からUXデザインを勉強している学生や、これからUXデザインを意識してみたい学生などなど、ぜひご参加ください!<br>
```
デザインではなくUXデザインの方が良いと思います。

2018-11-12 23:46 UTC, asukaokochi commented on content/events/othlohack2018.md
> +ご協賛いただいた企業様、差し入れをしていただいた皆様、本当にありがとうございました。<br>
```suggestion
また、ご協賛いただいた企業様、差し入れをしていただいた皆様、本当にありがとうございました。<br>
```
めっちゃ細かいですが、文章の頭に「また」とか「そして」とか接続詞があった方が読みやすいかもしれないです。

2018-11-12 23:46 UTC, asukaokochi commented on content/events/othlohack2018.md
> +興味が湧いた方は[こちら](https://othlotech.connpass.com/event/109132/)からご確認して下さい。
```suggestion
興味が湧いた方は[こちら](https://othlotech.connpass.com/event/109132/)からご確認下さい。
```
「興味が湧いた方」よりは「興味がある方」の方が良いかなと・・・（個人的な好みかもしれませんが）
あと、めっちゃ細かいですが、「ご確認してください」ではなく「ご確認ください」の方が日本語としておかしくないと思います。
IoTの方もよしなに修正して頂けると嬉しいです。

2018-11-12 23:57 UTC, Juju-62q commented on content/events/othlohack2018.md
> +やっほー!　こんにちはー!　OthloTechのオザキ([@sena0801masato](https://twitter.com/sena0801masato))です。<br>
これ、尾崎は改行位置がわかりやすいように意図的にやっているはずなので放置で良さそう！
俺が言っているのは知らないが故に意図もなく複数の表記を混ぜてしまうのは良く無いという話なので！

2018-11-13 00:04 UTC, Juju-62q requested changes
取り急ぎレビュー

2018-11-13 00:04 UTC, Juju-62q commented
動作している様子のスクショがあるとスマホでも確認できるのでいいかと思われ

2018-11-13 00:10 UTC, Juju-62q requested changes

2018-11-13 00:10 UTC, Juju-62q commented on content/events/othlohack2018.md
> +ご協賛いただいた企業様、差し入れをしていただいた皆様、本当にありがとうございました。<br>
今回は差し入れは無いはず

2018-11-13 00:10 UTC, Juju-62q commented on content/events/othlohack2018.md
> +そして、その花言葉を持つ花をオススメしてくれるというサービスでした。
1文に1つの意味というのはわかりやすいと言えばそうだけどここまでやると子供っぽく感じてしまうという印象なのでここまでやるなら箇条書きにしたほうがいいかなという気持ち。

2018-11-13 00:10 UTC, Juju-62q commented on content/events/othlohack2018.md
> +今回、実際の現場で働いているエンジニアさんやデザイナーさんをメンターとして多数お呼びし、参加者のどんな質問にも応えられるようなサポート体制を整えました。<br>
多数、必要かなぁ？

2018-11-13 00:10 UTC, Juju-62q commented on content/events/othlohack2018.md
> +今年は「特別な日をもっと彩る」というテーマをもとに、チームビルディングから始めました。<br>
テーマも強調したいなという気持ちになった

2018-11-13 04:00 UTC, haseaki0503 requested changes

2018-11-13 04:00 UTC, haseaki0503 commented on content/events/othlohack2018.md
> +やっほー!　こんにちはー!　OthloTechのオザキ([@sena0801masato](https://twitter.com/sena0801masato))です。<br>
```suggestion
やっほー!　こんにちはー!　OthloTech運営のオザキ([@sena0801masato](https://twitter.com/sena0801masato))です。<br>
```

2018-11-13 04:00 UTC, haseaki0503 commented on content/events/othlohack2018.md
> +OthloHack2018は、約40名の学生が参加し、14社もの企業にご協賛していただき、**東海最大級** の学生限定ハッカソンとなりました。<br>
「去年最大級になった」といっているのでなにか文言を変えてほしいです

2018-11-13 04:00 UTC, haseaki0503 commented on content/events/othlohack2018.md
> +そして、その花言葉を持つ花をオススメしてくれるというサービスでした。
> シェイミは、手書きの手紙からその手紙に合う花を選んでくれる「文咲み」(ふみえみ)というサービスを開発しました。<br>
> 具体的には、スマホで手紙の写真を撮り書かれている内容をOCRで分析。手紙に含まれる単語とその語に関連する花言葉を学習したデータを用いて、花ををいくつか提示するというものです。
そして、その花言葉を持つ花をオススメしてくれるというサービスでした。

2018-11-13 04:00 UTC, haseaki0503 commented on content/events/othlohack2018.md
> +ご協賛いただいた企業様、差し入れをしていただいた皆様、本当にありがとうございました。<br>
差し入れあったけ

2018-11-13 04:00 UTC, haseaki0503 commented on content/events/othlohack2018.md
> +2018/12/09(日)に、株式会社スタメンさんのご協力により、IoTに関連するLT会を開催します!<br>
このイベントは、スタメンさんには会場を貸してもらうのですが、IoTLTという団体と共催でIoTLTという会を開催するのです

2018-11-13 04:00 UTC, haseaki0503 commented on content/events/othlohack2018.md
> +内容はQiitaの趣旨に合うものであればいいので、初心者もぜひ参加しましょう!<br>
「ので」の前後がつながっていない気がします
> 内容はQiitaの趣旨に合うものであればいいので、初心者もぜひ参加しましょう!

2018-11-13 04:04 UTC, asukaokochi commented on content/events/othlohack2018.md
> +やっほー!　こんにちはー!　OthloTechのオザキ([@sena0801masato](https://twitter.com/sena0801masato))です。<br>
なるほど！了解です！

2018-11-13 04:44 UTC, Juju-62q commented on content/events/othlohack2018.md
> +ご協賛いただいた企業様、差し入れをしていただいた皆様、本当にありがとうございました。<br>
ない

2018-11-13 04:48 UTC, Juju-62q approved these changes

2018-11-13 12:23 UTC, asukaokochi approved these changes

2018-11-13 14:12 UTC, haseaki0503 requested changes

2018-11-13 14:12 UTC, haseaki0503 commented on content/events/othlohack2018.md
> +内容はQiitaの趣旨に合うものであれば、どんなことを書いてもいいので、初心者もぜひ参加しましょう!<br>
どちらかといえば、「初心者も」が気になります。

2018-11-13 14:12 UTC, haseaki0503 commented on content/events/othlohack2018.md
> +2018/12/09(日)に、株式会社スタメンさんに会場をお借りして、IoTLTというコミュニティと共催してIoTに関連するLT会を開催します!<br>
「〜して、〜して」が気になります。

2018-11-13 14:12 UTC, haseaki0503 commented on content/events/othlohack2018.md
> +そして、その花言葉を持つ花をオススメしてくれるというサービスでした。
「分析。」は意図しての文です。

2018-11-13 14:12 UTC, haseaki0503 commented on content/events/othlohack2018.md
> +OthloHack2018は、約40名の学生が参加し、14社もの企業にご協賛いただき、**東海圏の一大イベント** の学生限定ハッカソンとなりました。<br>
「**東海圏の一大イベント** の学生限定ハッカソン」は日本語おかしいと思います。

2018-11-13 15:12 UTC, haseaki0503 approved these changes

2018-11-14 04:41 UTC, merged